name: "Windows Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: app
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gigashit-calculator.py
          path: app

